export const IPC_EVENTS = {
  'GET_CONFIG': 'GET-CONFIG',
  'UPDATE_CONFIG': 'UPDATE-CONFIG',
  'GET_SCREEN_DIMENSION': 'GET-SCREEN-DIMENSION',
  'CREATE_OVERLAY': 'OVERLAY-CREATE-WINDOW',
  'SHOW_OVERLAY': 'OVERLAY-SHOW-WINDOW',
  'CLOSE_OVERLAY': 'OVERLAY-CLOSE-WINDOW',
  'OVERLAY_READY': 'OVERLAY-READY'
};

export type IpcEventsType = typeof IPC_EVENTS;
